version: '3'

services:
  node1:
    image: atlassian/jira-software:latest
    ports:
      - 30000:8080
    volumes:
      - ./jira-vmg-01:/var/atlassian/application-data/jira:Z
      - ./jira-sharedata:/var/atlassian/jira-sharedata:z
    environment:
      CATALINA_OPTS: -Datlassian.cluster.scale=true -DjvmRoute=node1 -Duser.timezone=Asia/Ho_Chi_Minh -Xms1048m -Xmx3500m
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535