version: "3"

services:
  nodejra:
    image: bachdangtuan/atlassian-jira-slim:9.17
    container_name: ${CONTAINER_NAME_APP}
    ports:
      - "30000:8080"
    volumes:
      - ./jira-01:/var/atlassian/application-data/jira:Z
      - ./jira-sharedata:/var/atlassian/jira-sharedata:z
    environment:
      - CATALINA_OPTS=-Datlassian.cluster.scale=true -DjvmRoute=node1 -Duser.timezone=${TZ} -Xms6048m -Xmx6048m
    ulimits:
      core: 0
      data: 1000000
      fsize: 1000000
      nproc: 4096
      nofile:
        soft: 1024
        hard: 4096
      memlock:
        soft: -1
        hard: -1
      stack: 8192
    networks:
      - network-bridge
  databasejira:
    image: postgres:13
    container_name: ${CONTAINER_NAME_DB}
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${TZ}
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
      stack: 8192
    volumes:
      - ./jira_postgres_data:/var/lib/postgresql/data
    networks:
      - network-bridge
networks:
  network-bridge:
    driver: bridge