version: "3"

services:
  nodejra:
    image: bachdangtuan/atlassian-jira-slim:9.17
    container_name: jira
    ports:
      - "30000:8080"
    volumes:
      - ./jira-01:/var/atlassian/application-data/jira:Z
      - ./jira-sharedata:/var/atlassian/jira-sharedata:z
    environment:
      - CATALINA_OPTS=-Datlassian.cluster.scale=true -DjvmRoute=node1 -Duser.timezone=Asia/Ho_Chi_Minh -Xms6048m -Xmx6048m
      - AGENT_PATH=/var/agent 
      - AGENT_FILENAME=atlassian-agent.jar
      - JAVA_OPTS="-javaagent:${AGENT_PATH}/${AGENT_FILENAME} ${JAVA_OPTS}"
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - network-bridge
  db:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=jiradb
      - POSTGRES_USER=jiradbuser 
      - POSTGRES_PASSWORD=123123 
    volumes:
      - ./jira_postgres_data:/var/lib/postgresql/data
    networks:
      - network-bridge

networks:
  network-bridge:

volumes:
  jira_postgres_data:
